# Generated by Django 4.2.2 on 2023-06-27 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0004_alter_incticket_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incticket',
            name='assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseApp.desksideengr'),
        ),
        migrations.AlterField(
            model_name='incticket',
            name='assignedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseApp.servicedesk'),
        ),
        migrations.AlterField(
            model_name='srticket',
            name='assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseApp.desksideengr'),
        ),
        migrations.AlterField(
            model_name='srticket',
            name='assignedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseApp.servicedesk'),
        ),
    ]
