# Generated by Django 4.2.2 on 2023-06-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0006_alter_incticket_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incticket',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
